# wrangler.toml
name = "m3u8-hunter"
main = "src/index.ts"

# 必须设置一个近期的兼容性日期
compatibility_date = "2025-07-25"

# 必须使用 v2 版本的 Node.js 兼容性标志。
# 这会启用 @cloudflare/puppeteer 所需的、由运行时原生支持的 Node.js API，
# 从而获得最佳性能和兼容性。
compatibility_flags = ["nodejs_compat_v2"]

# 必须使用服务绑定来连接到 Browser Rendering。
# 下方的内联表（inline table）语法是 Cloudflare 推荐的现代写法。
# 这会将一个名为 BROWSER 的变量注入到你的 Worker 环境中。
[browser]
binding = "BROWSER"

[assets]
directory = "./public"